version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/ci-cd-django
hooks:
  BeforeInstall:
      - location: scripts/pull_git_changes.sh
        timeout: 300
        runas: ubuntu
  AfterInstall:
      - location: scripts/after_install.sh
        timeout: 300
        runas: ubuntu