version: 0.0
os: linux
hooks:
  BeforeInstall:
      - location: scripts/clear_instance.sh
        timeout: 300
        runas: ubuntu
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/pull_git_changes.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/after_install.sh
        timeout: 300
        runas: ubuntu
  